import type { Metadata } from "next";
import { Outfit, Roboto_Slab, Oswald } from "next/font/google";
import { ToastContainer } from "react-toastify";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const outFit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const robotoFont = Roboto_Slab({
  variable: "--font-roboto",
  subsets: ["latin-ext"],
});

const oswaldFont = Oswald({
  variable: "--font-oswald",
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outFit.variable} ${robotoFont.variable} ${oswaldFont.variable} antialiased`}
      >
        {children}
        <ToastContainer />
        <NextTopLoader
          color="#CE0F2E"
          height={3}
          showSpinner={true}
          zIndex={1600}
        />
      </body>
    </html>
  );
}
